"""Rebuild every output from the extraction cache: rules, lookups, changes, self-check, web data.

  python -m navigator.run                  # after python -m navigator.extract
  python -m navigator.run --new-doc X01    # also report which addresses a newly added law affects
"""
import argparse
import datetime as dt
import hashlib
import json
import platform
import sys

from . import apply, changes, consolidate, corpus, export_web, plain, selfcheck
from .extract import MODEL


def write_manifest(a):
    """out/run_manifest.json: what went in and what came out, with hashes, so another person can check that a rerun
    of `python -m navigator.run` from the same cache reproduces the submission files exactly."""
    h = lambda p: hashlib.sha256(p.read_bytes()).hexdigest()
    root = corpus.ROOT
    cache = sorted((root / "cache" / "extractions").glob("*.json"))
    m = {
        "notice": "Not legal advice. Summaries of public law generated by software for information only.",
        "generated_at": dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds"),
        "command": "python -m navigator.run" + "".join(f" --new-doc {d}" for d in a.new_doc),
        "as_of": a.as_of, "extraction_model": MODEL, "python": platform.python_version(),
        "inputs": {
            "corpus_documents": {d: h(__import__("pathlib").Path(r["_base"]) / r["text_file"])
                                 for d, r in sorted(corpus.text_docs().items())},
            "supplied_corpus_documents": sorted(d for d in corpus.text_docs() if corpus.supplied(d)),
            "sample_addresses": h(corpus.STARTER / "data" / "sample_addresses.csv"),
            "change_tests": h(corpus.STARTER / "dev" / "change_tests.json"),
            "extract_prompt": h(root / "navigator" / "extract_prompt.md"),
            "extract_schema": h(root / "navigator" / "extract_schema.json"),
            "extraction_cache": {p.stem: h(p) for p in cache},
        },
        "outputs": {n: h(root / "out" / n) for n in ("rules.json", "lookups.json", "changes.json")},
        "audit_log": "audit/extraction_log.jsonl (one line per model call: model, time, prompt hash, tokens, rules kept/dropped)",
    }
    (root / "out" / "run_manifest.json").write_text(json.dumps(m, indent=1))


def main(argv=None):
    p = argparse.ArgumentParser()
    p.add_argument("--new-doc", action="append", default=[])
    p.add_argument("--as-of", default=apply.DEFAULT_AS_OF)
    a = p.parse_args(argv)
    consolidate.main()
    apply.main(a.as_of)
    changes.main(sum([["--new-doc", d] for d in a.new_doc], []))
    selfcheck.main()
    plain.main()
    export_web.main()
    write_manifest(a)
    print("Not legal advice. Outputs in out/ (rules.json, lookups.json, changes.json, selfcheck.txt, run_manifest.json)")


if __name__ == "__main__":
    main()
